### ISSUE TITLE
Not working with TypeScript in VS Code

### ISSUE THREAD

**Issue by OliverJAsh** [MicrosoftDocs/intellicode#47]
**Product and Version** [VS/VSCode]: VS Code
**OS Version** [macOS/Windows]: macOS 10.14.2
**IntelliCode Extension Version**: 1.1.2
**Target Platform or Language** [e.g. Node.js]: TypeScript

**Steps to Reproduce / Scenario:**

- Only this extension is enabled, plus no user settings: `code --user-data-dir temp .` and `--disable-extension` for every extension except this one
- Simple `.tsx` file

![image](https://user-images.githubusercontent.com/921609/50898245-7b26a400-1406-11e9-8a31-7b3da5eae730.png)

> Please copy and paste any details that are visible in the Output window logs for VS-IntelliCode

I don't see an option for this:

![image](https://user-images.githubusercontent.com/921609/50898306-add09c80-1406-11e9-95f5-c99209de8b53.png)

**Comment by jkeech** [comment]
This fix will be included in the next update of the VS Code IntelliCode extension.

**Comment by carpben** [comment]
After installing the extension I tested it on both .ts files and .tsx files. For me currently it works only on .ts files. 

I'm aware of https://github.com/MicrosoftDocs/intellicode/issues/24 and https://github.com/MicrosoftDocs/intellicode/issues/26. According to those the extension should not currently work on .tsx, but according to this issue it should. Can you clarify?

**Comment by nonameolsson** [comment]
I still experience issues with this. Is it fixed?

**Comment by minestarks** [comment]
@nonameolsson The original issue reported here is fixed, so you may be hitting a slightly different problem. Are you seeing issues in .tsx files, .ts files, or both? Could you describe the steps you're following and the exact behavior you're seeing? 

Please note there are two other bugs related to TypeScript - you could be hitting one of those. #32 #62

**Comment by nonameolsson** [comment]
> @nonameolsson The original issue reported here is fixed, so you may be hitting a slightly different problem. Are you seeing issues in .tsx files, .ts files, or both? Could you describe the steps you're following and the exact behavior you're seeing?
> 
> Please note there are two other bugs related to TypeScript - you could be hitting one of those. #32 #62

Sorry for a late reply. I still can't get the Intellicode to appear in the autocomplete list.

This is the output from VS IntelliCode
> Acquiring model 'intellisense-members' for javascript
> Querying IntelliCode service for available models.
> Cached model is up to date.

**Comment by sboc** [comment]
This is still an issue in 2023...

Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
